# Generated by Django 4.2.23 on 2025-11-24 14:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("paginas", "0002_avaliacao_delete_avaliação"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="texto",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="post",
            name="titulo",
            field=models.CharField(max_length=255),
        ),
    ]
