# Generated by Django 4.2.23 on 2025-11-24 14:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("paginas", "0003_alter_post_texto_alter_post_titulo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comentario",
            name="comentario",
            field=models.TextField(),
        ),
    ]
